name: sibna
description: Sibna Protocol v3.0.1 — Standalone pure Dart cryptographic modules
version: 3.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cryptography: ^2.7.0
  crypto: ^3.0.3
  convert: ^3.1.1

dev_dependencies:
  test: ^1.24.0
